# Generated by Django 3.2.16 on 2023-01-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_document_id', models.BigIntegerField(verbose_name='Document Id')),
                ('file_url', models.URLField(verbose_name='File Url')),
                ('file', models.FileField(blank=True, help_text='Excel file', null=True, upload_to='excel_files/')),
                ('output_file', models.FileField(blank=True, help_text='Output file', null=True, upload_to='downloaded/')),
                ('is_download', models.BooleanField(default=False, help_text='Is Downloaded')),
                ('is_finished', models.BooleanField(default=False, help_text='Is Finished')),
                ('retry_count', models.PositiveSmallIntegerField(default=0, help_text='Retry Count')),
            ],
            options={
                'verbose_name': 'Excel Değişken Dosyası',
                'verbose_name_plural': 'Excel Değişken Dosyaları',
                'ordering': ('id',),
            },
        ),
    ]
