# Generated by Django 3.2.16 on 2023-01-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_variables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfile',
            name='data',
            field=models.JSONField(blank=True, help_text='Data', null=True),
        ),
    ]
